### PR TITLE
Show mention count badge and unread * badge.

### PR DESCRIPTION
**Pull request by ttyniwa**
Show mention count badge and unread * badge like Slack app.
I tested only on Mac OSX.

### CODE REVIEW

**Comment by yuya-oc** [comment]
I have checked Slack app v1.3.3 (2813). I think `•` is better for Dock icon.

d4cc42299c9626f1c0ab87e946dc20e56c33414f version
d4cc42299c9626f1c0ab87e946dc20e56c33414f

`•` version
modified

Then, Slack app doesn't have tabs (In my memory, it uses "switch to ..." menu as same as web browsers). So we have to consider what is better character, I but I can't decide how to select. How do you think?
JFYI, please refer to screenshots.

d4cc42299c9626f1c0ab87e946dc20e56c33414f version
d4cc42299c9626f1c0ab87e946dc20e56c33414f

`•` version
modified

**Comment by ttyniwa** [comment]
I think • is better too!
fixed dc10546.

**Comment by ttyniwa** [comment]
no badge


unread mark


unread mark and mention

**Comment by yuya-oc** [comment]
Thank you for kind feedback! Well...I'm troubled.
If you don't mind, I'd like to use `•` also for tabs. It's more center-aligned than `*`.

**Comment by ttyniwa** [comment]
Sorry for my careless mistake.
I fixed it!

**Comment by yuya-oc** [comment]
Thanks.

**Pull request merged**
